import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from '@/components/ui/sidebar';
import { Sidebar } from '@/components/ui/sidebar';
import { SidebarContent } from '@/components/ui/sidebar';
import { SidebarMenu, SidebarMenuItem, SidebarMenuButton } from '@/components/ui/sidebar';
import { SidebarTrigger } from '@/components/ui/sidebar';
import Navbar from '@/components/ui/navbar';
import AppSidebar from '@/components/app-sidebar';
import { Toaster } from '@/components/ui/sonner';
import { ThemeProvider } from '@/components/theme-provider';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          defaultTheme="dark"
          storageKey="visionix-ui-theme"
        >
          <SidebarProvider>
            <div className="flex flex-row min-h-screen w-full">
              {/* 모바일 네브바 */}
              <Navbar />
              {/* 사이드바 - 데스크톱과 모바일 모두 지원 */}
              <AppSidebar />
              <main className="flex-1 bg-background min-h-screen h-full w-full overflow-x-hidden pt-14 md:pt-0">
                {children}
              </main>
            </div>
          </SidebarProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
